import { m, type Variants } from "framer-motion";
import { ArrowUpRight, MapPin, Clock3, Instagram } from "lucide-react";
import { Link } from "react-router-dom";
import { business, copy, photos, featuredMenu, formatPrice, orderLink, safeExternalLink, sectionIds } from "@/data/site";
import { WhatsappMark, ScrollReveal } from "@/components/SiteLayout";

const heroStagger: Variants = { hidden: {}, show: { transition: { staggerChildren: .1, delayChildren: .07 } } };
const heroLine: Variants = { hidden: { opacity: 0, y: 17 }, show: { opacity: 1, y: 0, transition: { duration: .46, ease: [.22, 1, .36, 1] } } };

export default function Home() {
  return <main id="contenido">
    <section className="hero" aria-labelledby="home-title"><div className="hero__photo"><img src={photos[4].src} alt="" fetchPriority="high" /></div><div className="hero__shade" /><div className="hero__grain" /><div className="hero__content"><m.div className="hero__copy" variants={heroStagger} initial="hidden" animate="show"><m.p className="eyebrow eyebrow--light" variants={heroLine}>{copy.eyebrow}</m.p><m.h1 id="home-title" variants={heroLine}>{copy.heroTitle}</m.h1><m.p className="hero__tagline" variants={heroLine}>{copy.heroSubtitle}</m.p><m.p className="hero__support" variants={heroLine}>{copy.heroSupport}</m.p><m.div className="hero__actions" variants={heroLine}><a className="button button--terracotta" href={business.whatsapp} {...safeExternalLink}><WhatsappMark />Pedir por WhatsApp<ArrowUpRight size={17} /></a><Link className="button button--outline" to="/menu">Ver menú<ArrowUpRight size={16} /></Link><Link className="button button--outline" to="/reservas">Reservar mesa<ArrowUpRight size={16} /></Link></m.div></m.div></div></section>
    <section className="about section-pad" id={sectionIds.history} aria-labelledby="history-title"><div className="section-wrap about__grid"><ScrollReveal className="about__visual"><div className="about__image-frame"><img src={photos[2].src} alt={photos[2].alt} loading="lazy" decoding="async" /></div></ScrollReveal><ScrollReveal className="about__copy" delay={.07}><h2 id="history-title">{copy.storyTitle}</h2><p>{copy.story.split(". ")[0]}.</p></ScrollReveal></div></section>
    <section className="home-menu section-pad" id={sectionIds.menu} aria-labelledby="home-menu-title"><div className="section-wrap"><ScrollReveal className="menu-heading"><h2 id="home-menu-title">{copy.menuTitle}</h2></ScrollReveal><div className="menu-grid home-menu__grid">{featuredMenu.map((item, index) => <ScrollReveal key={`${item.categoria}-${item.nombre}`} delay={index * .05}><a className="menu-item home-menu__item" href={orderLink(item.nombre)} {...safeExternalLink}><span className="menu-item__copy"><strong>{item.nombre}</strong><small>{item.categoria}</small></span><span className="menu-item__price">{formatPrice(item.precio)}</span></a></ScrollReveal>)}</div><ScrollReveal><Link className="text-link" to="/menu">Ver menú completo <ArrowUpRight size={16} /></Link></ScrollReveal></div></section>
    <section className="gallery-section section-pad" id={sectionIds.gallery} aria-labelledby="gallery-title"><div className="section-wrap"><ScrollReveal className="gallery-heading"><div><h2 id="gallery-title">{copy.galleryTitle}</h2><p className="section-lead">{copy.gallery}</p></div></ScrollReveal><div className="gallery-grid">{photos.map((photo, index) => <ScrollReveal key={photo.src} delay={index * .04} className={`gallery__tile gallery__tile--tile-${index}`}><img src={photo.src} alt={photo.alt} loading="lazy" decoding="async" /></ScrollReveal>)}</div></div></section>
    <section className="instagram-section section-pad" id={sectionIds.instagram} aria-labelledby="instagram-title"><div className="section-wrap"><ScrollReveal className="instagram-section__heading"><h2 id="instagram-title">{copy.instagramTitle}</h2><p>{copy.instagram}</p></ScrollReveal><div className="instagram-grid">{photos.map((photo, index) => <m.a className="instagram-grid__tile" key={photo.src} href={business.instagram} {...safeExternalLink} aria-label={`Instagram ${index + 1}: ${photo.alt}`} initial={{ opacity: 0, y: 13 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .18 }} transition={{ duration: .38, delay: index * .045 }}><img src={photo.src} alt={photo.alt} loading="lazy" decoding="async" /><span><Instagram size={18} aria-hidden="true" /></span></m.a>)}</div><ScrollReveal><a className="button button--terracotta" href={business.instagram} {...safeExternalLink}><Instagram size={17} />Seguir en Instagram<ArrowUpRight size={16} /></a></ScrollReveal></div></section>
    <section className="location section-pad" id={sectionIds.location} aria-labelledby="location-title"><div className="section-wrap"><ScrollReveal className="location-heading"><h2 id="location-title">{copy.locationTitle}</h2><a className="text-link" href={business.directions} {...safeExternalLink}>Abrir en Google Maps<ArrowUpRight size={16} /></a></ScrollReveal><ScrollReveal className="location__grid" delay={.05}><div className="map-frame"><iframe title="Mapa de Jalisco Mexican Grill en Lambaré, Paraguay" src={business.mapEmbed} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /></div><div className="location-card"><div className="location-card__block"><MapPin size={20} aria-hidden="true" /><p>{business.address}</p></div><div className="location-card__block"><Clock3 size={20} aria-hidden="true" /><div>{business.hours.map((hour) => <p key={hour}>{hour}</p>)}</div></div><a className="button button--dark" href={business.directions} {...safeExternalLink}>Abrir en Google Maps<ArrowUpRight size={16} /></a></div></ScrollReveal></div></section>
  </main>;
}
